export {default as Languages} from './Languages'
export {default as Skills} from './Skills'
export {default as ExtraSkills} from './ExtraSkills'
export {default as InfoBase} from './InfoBase'
export {default as Knowledge} from './Knowledge'